"""users added marks

Revision ID: e96865e4fa62
Revises: 59069a416ef2
Create Date: 2020-09-23 14:29:28.764869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96865e4fa62'
down_revision = '59069a416ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('ques', sa.String(length=350), nullable=True),
    sa.Column('a', sa.String(length=100), nullable=True),
    sa.Column('b', sa.String(length=100), nullable=True),
    sa.Column('c', sa.String(length=100), nullable=True),
    sa.Column('d', sa.String(length=100), nullable=True),
    sa.Column('ans', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('q_id'),
    sa.UniqueConstraint('ques')
    )
    op.add_column('user', sa.Column('marks', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_marks'), 'user', ['marks'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_marks'), table_name='user')
    op.drop_column('user', 'marks')
    op.drop_table('questions')
    # ### end Alembic commands ###
